---
title: "'Exit Try' solo puede aparecer dentro de una instrucción 'Try'"
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: 53c8ee60907db16ac97147100636e413f1cbc15e
ms.sourcegitcommit: 5c1abeec15fbddcc7dbaa729fabc1f1f29f12045
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 03/15/2019
ms.locfileid: "58043359"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try' solo puede aparecer dentro de una instrucción 'Try'
`Exit Try` solo puede aparecer dentro de una instrucción de bloque `Try` . O tiene una instrucción `Exit Try` redundante o la instrucción `Exit Try` aparece fuera de los límites del bloque `Try` correspondiente.  
  
 **Identificador de error:** BC30393  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
1.  Busque y quite la instrucción `Exit Try` innecesaria.  
  
2.  Mover el `Exit Try` instrucción a la ubicación adecuada dentro del código.  
  
## <a name="see-also"></a>Vea también

- [Try...Catch...Finally (instrucción)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
